Fix #1041
yhirose/cpp-httplib pull request #1132
Opened 2021-12-14 19:32 UTC by yhirose

2021-12-14 22:14 UTC, tsilia requested changes
I've checked and the logic I had described in the comment (see below) works fine: client doesn't close socket after each send.
So I'm suggesting you to re-implement `is_socket_alive` like this:
```cpp
inline bool is_socket_alive(socket_t sock) {
	if (detail::select_read(sock, 0, 0) == 0)
		return true;	// assume the socket is still alive
	char buf[1];
	const auto recv_res = recv(sock, &buf[0], sizeof(buf), MSG_PEEK);
	return (recv_res > 0);
}
```
Please note that the code doesn't handle possible errors.

Thanks!

2021-12-15 05:32 UTC, tsilia approved these changes
Works like a charm on my Linux system, thanks!

Though I'd recommend at least handle `select` returning `-1` with `errno` being set to `EBADF` (see the [man select](https://man7.org/linux/man-pages/man2/select.2.html))

2021-12-15 11:37 UTC, yhirose commented
@tsilia, thanks for the suggestion. I updated the code.

2021-12-16 19:24 UTC, tsilia requested changes
Please see the comments in this review.
TLDR; the logic is incorrect now and I'd suggest to revert to the previously approved code.

2021-12-16 19:52 UTC, yhirose commented on httplib.h
> +          is_alive = true;
Thanks for the suggestion. Somehow, I can't reproduce the problem "So now the client again always closes socket after each send"... But your suggestion sounds good to me, and I reverted and adjust is_socket_alive accordingly. I confirmed all the uni tests and your test (https://github.com/tsilia/poc-httplib-inf-keepalive) worked successfully. Please let me know if you find anything.

2021-12-16 20:53 UTC, tsilia commented on httplib.h
> +          is_alive = true;
> Somehow, I can't reproduce the problem "So now the client again always closes socket after each send"...

I'm totally positive that with that logic client always closed connection after each send:
1. There was a noticeable delay before each send (because client must reconnect again and again) which wouldn't come up with the correct logic (it's only noticeable using a 'real' network address, not `localhost`).
2. I've put some debug messages into the `detail::close_socket` function and around and these messages could be seen on every send:
```
./client 
Press enter key to stop client...
* Socket is not open!
Successfully posted 1882880898
!is_alive
close_socket
Successfully posted 1782988459
!is_alive
close_socket
Successfully posted 108701542
!is_alive
close_socket
Successfully posted 1110670616
!is_alive
close_socket
Successfully posted 1475065584

* Stopping client...
!is_alive
close_socket
Successfully posted 1284131091
close_socket
* Client stopped. Exiting...
```
3. You can see that that logic wasn't correct in terms of keeping the connection alive: the value of `is_alive` was first set to `true` when `val == 0` (`select` returned `0`), and then `is_alive` was unconditionally reassigned to the return value of `recv`.
Here's what was happening:
1. `select_read` returned 0 (socket had't been disconnected), `is_alive` was true.
2. `read_socket` returned 0 (again because no read/disconnect event), hence `is_alive` became false.

2021-12-16 21:04 UTC, tsilia approved these changes
It's working again, I double checked major cases.
Thanks!

2021-12-17 02:06 UTC, merged