Add Request::get_file_mutil_value interface.
yhirose/cpp-httplib pull request #918
Opened 2021-04-28 11:56 UTC by jingTian-z

Return multiple values corresponding to the key.

2021-04-28 12:35 UTC, yhirose commented
@jingTian-z, thanks for the contribution. Could you provide a Unit test for the method?

2021-05-02 12:28 UTC, yhirose commented
@jingTian-z, ping?

2021-05-02 12:37 UTC, jingTian-z commented
I am very sorry to see your email now. I am taking a holiday now but after my vacation, I think I can have a try.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yhirose ***@***.***>
发送时间: Sunday, May 2, 2021 8:29:06 PM
收件人: yhirose/cpp-httplib ***@***.***>
抄送: jingTian-z ***@***.***>; Mention ***@***.***>
主题: Re: [yhirose/cpp-httplib] Add Request::get_file_mutil_value interface. (#918)


@jingTian-z<https://github.com/jingTian-z>, ping?

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/yhirose/cpp-httplib/pull/918#issuecomment-830802198>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEB7PCGUDBJ436ZER4HP3TTTLVARFANCNFSM43W5WKCA>.

2021-05-07 01:13 UTC, yhirose requested changes

2021-05-07 01:13 UTC, yhirose commented on httplib.h
> +std::vector<MultipartFormData> Request::get_file_mutil_value(const char *key) const {
Could you add `inline` keyword at the beginning of the line as other methods do?

2021-05-19 18:38 UTC, yhirose commented
I'll close it for now until the code gets revised.

2021-05-19 18:38 UTC, closed without merging